@baseURL = http://localhost:5000
POST {{baseURL}}/todos
Content-type:application/json

{
      
    "title" : "todo 2" ,
    "completed" : "false" 
}

### 
Get {{baseURL}}/todos
 
### 
PUT {{baseURL}}/todos/11
Content-type: application/json

{
    
    "title" : "todo 4" ,
    "completed" : "false" 
}

### 
DELETE  {{baseURL}}/todos/14
Content-type: application/json

###
PATCH {{baseURL}}/todos/1
Content-Type:  application/json

{
    "title" : "edited title"
}

### 

POST {{baseURL}}/api/todos/producer 
Content-Type: application/json 
X-TOPIC: app.todos.save 


{
    "id" : 1,
    "title" : "title 1" , 
   "completed": false 
}